export const positionOptions = () => {
  return positionArray.map((item) => {
    return {
      label: item,
      value: item,
    };
  });
};

const positionArray = [
  'Marketing Specialist',
  'Marketing Manager',
  'Marketing Director',
  'Graphic Designer',
  'Marketing Research Analyst',
  'Marketing Communications Manager',
  'Marketing Consultant',
  'Product Manager',
  'Public Relations',
  'Social Media Assistant',
  'Brand Manager',
  'SEO Manager',
  'Content Marketing Manager',
  'Copywriter',
  'Media Buyer',
  'Digital Marketing Manager',
  'eCommerce Marketing Specialist',
  'Brand Strategist',
  'Vice President of Marketing',
  'Media Relations Coordinator',
  'Administrative Assistant',
  'Receptionist',
  'Office Manager',
  'Auditing Clerk',
  'Bookkeeper',
  'Account Executive',
  'Branch Manager',
  'Business Manager',
  'Quality Control Coordinator',
  'Administrative Manager',
  'Business Analyst',
  'Risk Manager',
  'Human Resources',
  'Office Assistant',
  'Secretary',
  'Office Clerk',
  'File Clerk',
  'Account Collector',
  'Administrative Specialist',
  'Executive Assistant',
  'Program Administrator',
  'Program Manager',
  'Administrative Analyst',
  'Data Entry',
  'CEO—Chief Executive Officer',
  'COO—Chief Operating Officer',
  'CFO—Chief Financial Officer',
  'CIO—Chief Information Officer',
  'CTO—Chief Technology Officer',
  'CMO—Chief Marketing Officer',
  'CHRO—Chief Human Resources Officer',
  'CDO—Chief Data Officer',
  'CPO—Chief Product Officer',
  'CCO—Chief Customer Officer',
  'Team Leader',
  'Manager',
  'Assistant Manager',
  'Executive',
  'Director',
  'Coordinator',
  'Administrator',
  'Controller',
  'Officer',
  'Organizer',
  'Supervisor',
  'Superintendent',
  'Head',
  'Overseer',
  'Foreman',
  'Controller',
  'Principal',
  'President',
  'Lead',
  'Computer Scientist',
  'IT Professional',
  'UX Designer & UI Developer',
  'SQL Developer',
  'Web Designer',
  'Web Developer',
  'Help Desk Worker/Desktop Support',
  'Software Engineer',
  'Data Entry',
  'DevOps Engineer',
  'Computer Programmer',
  'Network Administrator',
  'Information Security Analyst',
  'Artificial Intelligence Engineer',
  'Cloud Architect',
  'IT Manager',
  'Technical Specialist',
  'Application Developer',
  'Sales Associate',
  'Sales Representative',
  'Sales Manager',
  'Retail Worker',
  'Store Manager',
  'Sales Representative',
  'Sales Manager',
  'Real Estate Broker',
  'Sales Associate',
  'Cashier',
  'Store Manager',
  'Account Executive',
  'Account Manager',
  'Area Sales Manager',
  'Direct Salesperson',
  'Director of Inside Sales',
  'Outside Sales Manager',
  'Sales Analyst',
  'Market Development Manager',
  'B2B Sales Specialist',
  'Sales Engineer',
  'Merchandising Associate',
  'Construction Worker',
  'Taper',
  'Plumber',
  'Heavy Equipment Operator',
  'Vehicle or Equipment Cleaner',
  'Carpenter',
  'Electrician',
  'Painter',
  'Welder',
  'Handyman',
  'Boilermaker',
  'Crane Operator',
  'Building Inspector',
  'Pipefitter',
  'Sheet Metal Worker',
  'Iron Worker',
  'Mason',
  'Roofer',
  'Solar Photovoltaic Installer',
  'Well Driller',
  'CEO',
  'Proprietor',
  'Principal',
  'Owner',
  'President',
  'Founder',
  'Administrator',
  'Director',
  'Managing Partner',
  'Managing Member',
  'Credit Authorizer',
  'Benefits Manager',
  'Credit Counselor',
  'Accountant',
  'Bookkeeper',
  'Accounting Analyst',
  'Accounting Director',
  'Accounts Payable/Receivable Clerk',
  'Auditor',
  'Budget Analyst',
  'Controller',
  'Financial Analyst',
  'Finance Manager',
  'Economist',
  'Payroll Manager',
  'Payroll Clerk',
  'Financial Planner',
  'Financial Services Representative',
  'Finance Director',
  'Commercial Loan Officer',
  'Engineer',
  'Mechanical Engineer',
  'Civil Engineer',
  'Electrical Engineer',
  'Assistant Engineer',
  'Chemical Engineer',
  'Chief Engineer',
  'Drafter',
  'Engineering Technician',
  'Geological Engineer',
  'Biological Engineer',
  'Maintenance Engineer',
  'Mining Engineer',
  'Nuclear Engineer',
  'Petroleum Engineer',
  'Plant Engineer',
  'Production Engineer',
  'Quality Engineer',
  'Safety Engineer',
  'Sales Engineer',
  'Mentor',
  'Tutor/Online Tutor',
  'Teacher',
  'Teaching Assistant',
  'Substitute Teacher',
  'Preschool Teacher',
  'Test Scorer',
  'Online ESL Instructor',
  'Professor',
  'Assistant Professor',
  'Graphic Designer',
  'Artist',
  'Interior Designer',
  'Video Editor',
  'Video or Film Producer',
  'Playwright',
  'Musician',
  'Novelist/Writer',
  'Computer Animator',
  'Photographer',
  'Camera Operator',
  'Sound Engineer',
  'Motion Picture Director',
  'Actor',
  'Music Producer',
  'Director of Photography',
  'Nurse',
  'Travel Nurse',
  'Nurse Practitioner',
  'Doctor',
  'Caregiver',
  'CNA',
  'Physical Therapist',
  'Pharmacist',
  'Pharmacy Assistant',
  'Medical Administrator',
  'Medical Laboratory Tech',
  'Physical Therapy Assistant',
  'Massage Therapy',
  'Dental Hygienist',
  'Orderly',
  'Personal Trainer',
  'Massage Therapy',
  'Medical Laboratory Tech',
  'Phlebotomist',
  'Medical Transcriptionist',
  'Telework Nurse/Doctor',
  'Reiki Practitioner',
  'Waiter/Waitress',
  'Server',
  'Chef',
  'Fast Food Worker',
  'Barista',
  'Line Cook',
  'Cafeteria Worker',
  'Restaurant Manager',
  'Wait Staff Manager',
  'Bus Person',
  'Restaurant Chain Executive',
  'Political Scientist',
  'Chemist',
  'Conservation Scientist',
  'Sociologist',
  'Biologist',
  'Geologist',
  'Physicist',
  'Astronomer',
  'Atmospheric Scientist',
  'Molecular Scientist',
  'Journalist',
  'Copy Editor',
  'Editor/Proofreader',
  'Content Creator',
  'Speechwriter',
  'Communications Director',
  'Screenwriter',
  'Technical Writer',
  'Columnist',
  'Public Relations Specialist',
  'Proposal Writer',
  'Content Strategist',
  'Grant Writer',
  'Video Game Writer',
  'Translator',
  'Film Critic',
  'Copywriter',
  'Travel Writer',
  'Social Media Specialist',
  'Ghostwriter',
];
